### ISSUE TITLE
Error with Photoshop CC 2015.5

### ISSUE THREAD

**Issue by ehollinge** [bogdanrybak/spritesheet-generator#1]
Hello, your script looks super helpful, however I am getting an error when I run it:
"An error occured, please submit a bug report. Error: Error: General Photoshop error occurred. This functionality may not be available in this version of Photoshop.  -The command “Select” is not currently available."
Ideas?  
Thanks and let me know if you need more info!

**Comment by bogdanrybak** [comment]
Sorry about the late reply. Could you also link the file this is occurring with? Then I can test it! Thanks!

**Comment by OutThisLife** [comment]
Getting the same thing here.  In my case it's just a simple psd.

**Comment by bogdanrybak** [comment]
Hi, which version of Photoshop? could you send the PSD over so I can debug it? One thing I can think of is that it won't work if any of your frames have no pixels in them. The selection tool errors out then.

**Comment by RobbieOnGithub** [comment]
I usually do my cel animations using a photoshop video layer. When doing so I had the same issue  as the others noted above. I had to save my anim as a gif (losing transparency) and then re-imported it to Photoshop as a frame-by-frame animation and then the script worked. 

Any chance you'll make the script work for video layers too? My gif export to re-import route screws up transparencies so it isn't ideal... This would be very helpful if possible. Attached is a super quick anim using a photoshop video layer for reference.

[test-water.zip](https://github.com/bogdanrybak/spritesheet-generator/files/588216/test-water.zip)

**Comment by bogdanrybak** [comment]
Apologies for getting back so late about this.

For the others, are you also trying to use it on a video timeline?
I'm really not sure about using the video layer. If there's a button in Photoshop's UI that lets you go to a next frame, then I can record that and it is doable. I'll try to see if that's possible when I can get my hands on Photoshop CC.

Thanks for providing the file!
