### ISSUE TITLE
Issue with Adobe Photoshop CC 2017

### ISSUE THREAD

**Issue by justvcreative** [bogdanrybak/spritesheet-generator#2]
Here is a screenshot of an error after I installed the script, restarted photoshop, and tried to run the script.
<img width="420" alt="screen shot 2016-12-10 at 5 49 41 pm" src="https://cloud.githubusercontent.com/assets/12233815/21076739/573f968e-bf01-11e6-9f5b-e0fcbe22f61d.png">

**Comment by bogdanrybak** [comment]
Hey! It got saved with the whole github page of the script. You just need the script itself which can be found under the "raw" link or by clicking "Clone or download" in github.

[Here's a link to the raw version](https://raw.githubusercontent.com/bogdanrybak/spritesheet-generator/master/Spritesheet%20Generator.jsx )

Cheers
