### ISSUE TITLE
I CAN'T GENERATE SPRITE SHEET USING YOUR SCRIPT

### ISSUE THREAD

**Issue by GeekSauce** [bogdanrybak/spritesheet-generator#3]
SO I TRIED TO USE YOUR SCRIPT ON MY PHOTOSHOP CC. AND GOT AN ERROR MESSAGE.

![bug](https://cloud.githubusercontent.com/assets/26894964/24648312/d6d796e0-1955-11e7-99dd-69a47db1bda5.png)

SORRY FOR CAPSLOCK BUT I AM DESPERATE AS I HAVE A CLASS TO TEACH NEXT WEEK AND I NEED THE STUDENTS TO CREATE SPRITE SHEETS FOR THEIR VIDEO GAME. PLEASE REVERT ASAP. THANK YOUUUU

**Comment by bogdanrybak** [comment]
Hey, I'm not sure if that's the issue but you don't seem to be using Photoshop's animator feature, this script is only for being used with the animator. If you want something that just uses layer structure then use [SpritePlane](https://github.com/mediochrea/SpritePlane)

**Comment by GeekSauce** [comment]
Hey!

Thank you for your prompt reply. I'll try Sprite Plane and will see how it
pans out.

Cheers from Singapore!
