### ISSUE TITLE
The command "Select" is not currently available

### ISSUE THREAD

**Issue by dmauro** [bogdanrybak/spritesheet-generator#6]
![Screen Shot 2019-04-20 at 9 47 47 AM](https://user-images.githubusercontent.com/473366/56458180-6173f180-6351-11e9-910b-d6900b4bc061.png)

Using Photoshop CC 20.0.0. All the layers are in the animator timeline. I've previously used this successfully before, and it seems to have stopped working for reasons beyond me. Here's an example of what I'm working with:

![Screen Shot 2019-04-20 at 9 52 58 AM](https://user-images.githubusercontent.com/473366/56458237-1c9c8a80-6352-11e9-8453-fd678acdbe6a.png)

The script generates two new documents (one prepended with _tmp) before it gives up with that error.

**Comment by bogdanrybak** [comment]
The script doesn't work with Timeline. You have to use Frame Animation.

![image](https://user-images.githubusercontent.com/2091383/56527838-47d2d580-651c-11e9-94e1-a32d7dd6d61f.png)

**Comment by dmauro** [comment]
( >___<) Sorry, I definitely knew this and that's what I was doing before that made it work, it had just been a minute since I used it and I forgot about that conversion step. Thanks for clearing this up though!
